base_model: someone13574/Mistral-7B-v0.1-sharded
base_model_config: someone13574/Mistral-7B-v0.1-sharded
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: ../../datasets/samantha-1.1.json
    type: sharegpt:chat
dataset_prepared_path: last_run_prepared
val_set_size: 0.01
output_dir: ../mistral-7b-samamantha-qlora-out

adapter: qlora
lora_model_dir:

sequence_len: 2048
sample_packing: false

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: mistral-7b-samantha
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 8
num_epochs: 1
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: false
fp16: true
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: false

warmup_steps: 10
eval_steps: 20
eval_table_size:
save_steps: 50
save_total_limit: 2
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
